[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
] }
getrandom = { version = "0.2.12", features = ["js"], default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]
